
//product list

export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCES = 'PRODUCT_LIST_SUCCES'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'
//product details
export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST'
export const PRODUCT_DETAIL_SUCCES = 'PRODUCT_DETAIL_SUCCES'
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL'
//USER DETAIL
export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST'
export const USER_DETAIL_SUCCES = 'USER_DETAIL_SUCCES'
export const USER_DETAIL_FAIL = 'USER_DETAIL_FAIL'
//USER update PROFILE
export const USER_UPDATE_REQUEST = 'USER_UPDTAE_REQUEST'
export const USER_UPDATE_SUCCES = 'USER_UPDTAE_SUCCES'
export const USER_UPDATE_FAIL = 'USER_UPDTAE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDTAE_RESET'
//card item
export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
// shipping  address
export const CART_SAVE_SHIPPING_ADDRESS='CART_SAVE_SHIPPING_ADDRESS'
//Paymentmethod
export const CART_SAVE_PAYMENT='CART_SAVE_PAYMENT'
