const products =[
    {
        _id :'1',
        name:'name1',
        image:'img/mazarati.jpg',
        description:' wow',
        brand:'bmw',
        category:'benzin',
        price: 150.13,
        stock: 3,
        rating:0.5,
        numReviews:5,
    },
    {
        _id :'2',
        name:'name2',
        image:'img/mercedes.jpg',
        description:' wow',
        brand:'bmw',
        category:'benzin',
        price: 150.13,
        stock: 0,
        rating:3,
        numReviews:5,
    },
    {
        _id :'3',
        name:'name3',
        image:'img/tesla.jpg',
        description:' wow',
        brand:'bmw',
        category:'benzin',
        price: 150.13,
        stock: 3,
        rating:1.5,
        numReviews:5,
    },
    {
        _id :'4',
        name:'name4',
        image:'img/mazarati.jpg',
        description:' wow',
        brand:'bmw',
        category:'benzin',
        price: 150.13,
        stock: 3,
        rating:2.5,
        numReviews:5,
    },
    ]
    export default products